/**
 * LumiSport 管理员端 - 商品管理
 */
var products = [
  { id:'p1', icon:'🏡', name:'特调鸡尾酒', cat:'酒水饮料', price:80, origPrice:128, stock:25, desc:'精选伏特加搭配青柠汁与蔓越莓' },{ id:'p2', icon:'🖈', name:'威士忌 Shot', cat:'酒水饮料', price:50, origPrice:88, stock:15, desc:'苏格兰单一麦芽 12 年陈酿' },{ id:'p3', icon:'🏑', name:'精酿啤酒', cat:'酒水饮料', price:30, origPrice:58, stock:48, desc:'比利时修道院风格精酿' },{ id:'p4', icon:'🏎', name:'红酒一杯', cat:'酒水饮料', price:60, origPrice:98, stock:8, desc:'智利赤霞珠，单宁柔和' },{ id:'p5', icon:'🝏', name:'冰桶套餐', cat:'酒水饮料', price:120, origPrice:198, stock:3, desc:'6瓶科罗娜+冰桶+青柠角' },{ id:'p6', icon:'🜌', name:'莫吉托', cat:'酒水饮料', price:40, origPrice:68, stock:32, desc:'白朗姆+薄荷+青柠' },{ id:'p7', icon:'🛏', name:'豪华大床房', cat:'客房服务', price:500, origPrice:888, stock:5, desc:'含双早·延迟退房至14:00' },{ id:'p8', icon:'🧹', name:'客房清洁', cat:'客房服务', price:30, origPrice:50, stock:99, desc:'标准客房打扫服务' },{ id:'p9', icon:'🍽', name:'送餐服务', cat:'客房服务', price:20, origPrice:30, stock:99, desc:'24小时客房送餐' },{ id:'p10', icon:'🧸', name:'Lumi熊公仔', cat:'周边手办', price:150, origPrice:258, stock:12, desc:'限量版发光公仔·15cm' },{ id:'p11', icon:'👕', name:'主题T恤', cat:'周边手办', price:90, origPrice:168, stock:20, desc:'LumiSport 联名款' },{ id:'p12', icon:'🔑', name:'纪念钥匙扣', cat:'周边手办', price:25, origPrice:48, stock:60, desc:'金属材质·激光刻字' },{ id:'p13', icon:'🍿', name:'爆米花', cat:'零食小吃', price:15, origPrice:25, stock:80, desc:'焦糖口味·大桶装' },{ id:'p14', icon:'🍫', name:'手工巧克力', cat:'零食小吃', price:35, origPrice:58, stock:22, desc:'比利时进口·礼盒装' },{ id:'p15', icon:'🥜', name:'坚果拼盘', cat:'零食小吃', price:28, origPrice:45, stock:35, desc:'腰果+杏仁+开心果' }
];
var categories = ['酒水饮料', '客房服务', '周边手办', '零食小吃', '其他'];

function renderStore(){var catsHtml='<div class="store-cat'+(selectedStoreCat==='全部'?' active':'')+'" onclick="selectStoreCat(\'全部\')">全部</div>';categories.forEach(function(cat){catsHtml+='<div class="store-cat'+(selectedStoreCat===cat?' active':'')+'" onclick="selectStoreCat(\''+cat+'\')">'+cat+'</div>'});document.getElementById('storeCats').innerHTML=catsHtml;var list=selectedStoreCat==='全部'?products:products.filter(function(p){return p.cat===selectedStoreCat});var html='';if(list.length===0){html='<div style="text-align:center;padding:30px 0;color:var(--muted);font-size:0.78em;">📭 该分类暂无商品</div>'}else{list.forEach(function(p){var sc=p.stock>10?'stock-ok':(p.stock>0?'stock-low':'stock-out');var stText=p.stock>0?p.stock:'售罄';html+='<div class="store-prod"><div class="sp-icon">'+p.icon+'</div><div class="sp-info"><div class="sp-name">'+p.name+'</div><div class="sp-meta"><span>'+p.price+'</span> 💎 · ￥'+p.origPrice+' · '+p.desc+'</div></div><div class="sp-stock"><div class="val '+sc+'">'+stText+'</div><div class="lbl">库存</div></div><button class="btn-del" onclick="removeProduct(\''+p.id+'\')" title="下架">✕</button></div>'})}document.getElementById('storeProducts').innerHTML=html;document.getElementById('storeVenueText').textContent=currentStore}
function removeProduct(id){var p=products.find(function(x){return x.id===id});if(!p)return;showConfirm('确定下架 '+p.icon+' '+p.name+' 吗？\n库存 '+p.stock+' · 兑换价 '+p.price+' 💎',function(){products=products.filter(function(x){return x.id!==id});renderStore();toastMsg('已下架 '+p.icon+' '+p.name)})}
function selectStoreCat(cat){selectedStoreCat=cat;renderStore()}
function simulateUpload(){var icons=['🏡','🖈','🏑','🏎','🝏','🜌','🛏','🧹','🍽','🧸','👕','🔑','🍿','🍫','🥜','🎁','📦','⭐'];var icon=icons[Math.floor(Math.random()*icons.length)];document.getElementById('addProdIcon').value=icon;document.getElementById('imgUploadPreview').innerHTML='<span style="font-size:2em;">'+icon+'</span><span style="display:block;font-size:0.65em;color:var(--muted);margin-top:2px;">已上传</span>'}
function onAddPriceInput(){var inp=document.getElementById('addProdPrice');var v=parseInt(inp.value)||0;var hint=document.getElementById('addPriceHint');if(inp.value&&(!Number.isInteger(parseFloat(inp.value))||v<1)){hint.textContent='兑换价必须为 ≥1 的整数'}else{hint.textContent=''}}
function onAddOrigInput(){var inp=document.getElementById('addProdOrig');var v=parseFloat(inp.value);var hint=document.getElementById('addOrigHint');if(inp.value){if(isNaN(v)||v<=0){hint.textContent='原价必须为正数'}else{var d=(inp.value.split('.')[1]||'').length;if(d>2){hint.textContent='原价最多2位小数'}else{hint.textContent=''}}}else{hint.textContent=''}}
function showAddProduct(){document.getElementById('addProdName').value='';document.getElementById('addProdIcon').value='';document.getElementById('imgUploadPreview').innerHTML='<span class="img-upload-plus">+</span><span class="img-upload-text">拍照 / 上传照片</span>';document.getElementById('addProdCat').value='酒水饮料';document.getElementById('addProdPrice').value='';document.getElementById('addPriceHint').textContent='';document.getElementById('addProdOrig').value='';document.getElementById('addOrigHint').textContent='';document.getElementById('addProdStock').value='100';document.getElementById('addProdDesc').value='';document.getElementById('addProductModal').classList.remove('hidden')}
function addProduct(){var name=document.getElementById('addProdName').value.trim();var icon=document.getElementById('addProdIcon').value.trim();var cat=document.getElementById('addProdCat').value;var price=parseInt(document.getElementById('addProdPrice').value)||0;var orig=parseFloat(document.getElementById('addProdOrig').value);var stock=parseInt(document.getElementById('addProdStock').value)||0;var desc=document.getElementById('addProdDesc').value.trim();if(!name)return toastMsg('请输入商品名称');if(!icon)return toastMsg('请上传商品图片');if(price<1)return toastMsg('兑换价必须为 ≥1 的整数');if(isNaN(orig)||orig<=0)return toastMsg('原价必须为正数');var decimals=(document.getElementById('addProdOrig').value.split('.')[1]||'').length;if(decimals>2)return toastMsg('原价最多2位小数');products.push({id:'p'+Date.now(),icon:icon,name:name,cat:cat,price:price,origPrice:orig,stock:stock,desc:desc||name});document.getElementById('addProductModal').classList.add('hidden');if(selectedStoreCat!=='全部'&&selectedStoreCat!==cat)selectedStoreCat=cat;renderStore();toastMsg('✅ '+icon+' '+name+' 已添加')}
